# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/156QTrEX2MVqkS-EDlxBSjfGhSA6F3Fwj
"""

import streamlit as st
import pickle
import pandas as pd

tfidf=pickle.load(open('tfidf.pkl','rb'))
sent_model=pickle.load(open('logreg.pkl','rb'))

import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = stopwords.words('english')

def clean_text(text):
    text = text.lower() #convert to lowercase
    text = re.sub(r'[^a-z\s]', '', text) #Removes numbers , symbols, punctuations
    words = text.split() #splits into words
    words = [word for word in words if word not in stop_words] #Removes common stopwords and keeps meaningful words only
    return " ".join(words) #Joins remaining words back into a sentence

st.set_page_config(page_title="Sentiment Analyser", page_icon="💬")
st.title("💬 Product Review Sentiment Analyser")
st.write("Enter a product review to predict its sentiment.")

review = st.text_area("📝 Enter Review Here", height=150)

if st.button("Analyse Sentiment"):
    if review.strip() == "":
        st.warning("⚠️ Please enter a review!")
    else:
        cleaned = clean_text(review)
        vectorized = tfidf.transform([cleaned])
        prediction =sent_model.predict(vectorized)[0]
        probability =sent_model.predict_proba(vectorized).max()

        if prediction == "Positive":
            st.success(f"✅ Sentiment : **{prediction}** (Confidence : {probability:.2%})")
        elif prediction == "Negative":
            st.error(f"❌ Sentiment : **{prediction}** (Confidence : {probability:.2%})")
        else:
            st.info(f"😐 Sentiment : **{prediction}** (Confidence : {probability:.2%})")





